version:  '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD:  "ayamProd123"
      POSTGRES_DB: "eagle_eye_prod"